# Generated by Django 5.2.8 on 2026-01-18 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address_line1',
            new_name='delivery_address_line1',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address_line2',
            new_name='delivery_address_line2',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='city',
            new_name='delivery_city',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='country',
            new_name='delivery_country',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='email',
            new_name='delivery_email',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='full_name',
            new_name='delivery_full_name',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='state',
            new_name='delivery_state',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='zip_code',
            new_name='delivery_zip_code',
        ),
    ]
