# Generated by Django 5.2.5 on 2026-01-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='delivery_phone',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
