# Generated by Django 5.2.5 on 2026-01-26 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_shippingaddress_delivery_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name_plural': 'Shipping Address'},
        ),
    ]
